services:
  cage_fusion_nuisance_api:
    build: .
    volumes:
      - ./checkpoints:/checkpoints
      - ./logs:/logs
      - ./pred_results:/pred_results
    ports:
      - "10002:10002"
    environment:
      CHECKPOINT_DIR: /checkpoints/nuisance-pred
      CAGE_FUSION_LOG_DIR: /logs
      PRED_RES_ROOT_DIR: /pred-results
      MODEL_NAME: DeepChem-ChemBERTa-77M-MTR-CoAttn-1-cross-aux-fgprompt
      MODEL_FILE: latest_checkpoint.pt
      BATCH_SIZE: "24"

    networks:
      - daikon-be-net

networks:
  daikon-be-net:
    external: true
    name: daikon-be-net